services:
  hinghwa-dict-uni-app:
    build: .
    image: "${SERVICE_NAME}"
    container_name: "${SERVICE_NAME}"
    environment: 
      VITE_BACKEND_URL: "${BACKEND_URL}"
    labels:
      - "traefik.http.routers.${SERVICE_NAME}.rule=${HOST_ADDRESS}"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${PORT:-80}"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=${SERVICE_NAME}-compress"
      - "traefik.http.middlewares.${SERVICE_NAME}-compress.compress=true"
    networks:
      - traefik-global-proxy

networks:
  traefik-global-proxy:
    external: true